version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task: deps
      - task: test
      - task: fmt
      - task: lint
      - task: build
      - task: vuln

  deps:
    cmds:
      - go mod tidy

  deps:update:
    cmds:
      - go get -u ./...
      - task: test

  fmt:
    cmds:
      - go run mvdan.cc/gofumpt@latest -w ./
      - npx prettier -w *.md

  test:
    cmds:
      - go test ./...

  bench:
    cmds:
      - go test ./pkg/epubproc/ -bench=.

  vet:
    cmds:
      - go vet ./...

  lint:
    cmds:
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.4 run

  vuln:
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  modernize:
    cmds:
      - go run golang.org/x/tools/go/analysis/passes/modernize/cmd/modernize@latest -fix ./...
      - task: test
  
  build:
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/epub-search ./cmd/epub-search
