version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task: install
      - task: test
      - task: lint
      - task: build

  install:
    cmds:
      - go mod tidy

  upgrade:
    cmds:
      - go get -u ./...

  install-tools:
    cmds:
      - go install mvdan.cc/gofumpt@latest
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.2
      - if command -v brew &> /dev/null; then brew install go-task; fi

  fmt:
    cmds:
      - gofumpt -w ./

  test:
    cmds:
      - go test ./...

  vet:
    cmds:
      - go vet ./...

  lint:
    cmds:
      - golangci-lint run

  build:
    cmds:
      - mkdir -p ./bin
      - go build -o ./bin/epub-search ./cmd/epub-search
